language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t richarddundas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true richarddundas/docker-react npm run test -- --coverage